databases:
  - name: bugdet_app
    databaseName: bugdet_app
    user: bugdet_app_user

services:
  - type: web
    name: BugiBugy
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bugdet_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false